In [68]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [69]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [70]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [83]:
def Jacobi(A,b,x0,itmax=1000,tolerancia=1e-14):
    
    x = x0.copy()
    u = x.copy()
    sumk = x.copy()
    
    residuo = np.linalg.norm( np.dot(A,x) - b)
    
    print(residuo)
    
    it = 0
    
    while residuo >= tolerancia and it < itmax:
        
        
        u[:] = 0
        sumk[:] = 0.
        
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if i != j:
                    sumk[i] += A[i,j]*x[j]
            #print(sumk)
        
            u[i] = (b[i] - sumk[i])/A[i,i]
        
        
        x = u.copy()
        
        #print(x,residuo)
        # Norma infinita
        residuo = np.max(np.abs(np.dot(A,x) - b))
        # Norma griega
        #residuo = np.linalg.norm( np.dot(A,x) - b)
        
        it += 1
        
        if residuo > 1000:
            print('No calculable con Jacobi')
            x[:] = 0.
            break
        
    return x,it

In [84]:
Jacobi(A,b,np.array([0.,0.,0.]))

7.681145747868608


(array([1., 1., 1.]), 31)

In [73]:
#A = np.random.randint(-10,10,size=(5,5))
#b = np.random.randint(-10,10,size=5)

In [74]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [75]:
Jacobi(A,b,np.array([0.,0.,0.,0.,0.]))

ValueError: shapes (3,3) and (5,) not aligned: 3 (dim 1) != 5 (dim 0)

In [76]:
def GetT(A):
    
    M,N = A.shape
    
    D = np.zeros((M,N))
    R = D.copy()
    T = R.copy()
    
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if i == j:
              #  print(A[i,j])
               # print(1./A[i,j])
                D[i,j] = 1./A[i,j]
            else:
                R[i,j] = A[i,j]
    
 #   print(D)
 #   print(R)
    return np.dot(D,R)

In [77]:
T = GetT(A)

In [78]:
Values,Vectors = np.linalg.eig(T)

In [79]:
Values

array([-0.33333333+0.j        ,  0.16666667+0.23570226j,
        0.16666667-0.23570226j])

In [80]:
np.abs(Values)

array([0.33333333, 0.28867513, 0.28867513])