In [3]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [4]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [5]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [31]:
def Jacobi(A,b,x0,itmax=1000,tolerancia=1e-9):
    
    x = x0.copy()
    u = x.copy()
    sumk = x.copy()
    
    residuo = np.linalg.norm( np.dot(A,x) - b)
    
    print(residuo)
    
    it = 0
    
    while residuo >= tolerancia and it < itmax:
        
        
        u[:] = 0
        sumk[:] = 0.
        
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if i != j:
                    sumk[i] += A[i,j]*x[j]
            #print(sumk)
        
            u[i] = (b[i] - sumk[i])/A[i,i]
        
        
        x = u.copy()
        
        #print(x,residuo)
       
        residuo = np.linalg.norm( np.dot(A,x) - b)
        
        it += 1
        
        if residuo > 1000:
            print('No calculable con Jacobi')
            x[:] = 0.
            break
        
    return x,it

In [32]:
Jacobi(A,b,np.array([0.,0.,0.]))

7.681145747868608


(array([1., 1., 1.]), 21)

In [34]:
A = np.random.randint(-10,10,size=(5,5))
b = np.random.randint(-10,10,size=5)

In [35]:
np.linalg.solve(A,b)

array([ 1.45588484,  0.46486029, -0.73090601,  1.58933108,  0.57713802])

In [36]:
Jacobi(A,b,np.array([0.,0.,0.,0.,0.]))

13.96424004376894
No calculable con Jacobi


(array([0., 0., 0., 0., 0.]), 7)

In [ ]:
def GetT(A):
    
    